# Generated by Django 4.0.4 on 2022-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='purchasing_price',
        ),
        migrations.AddField(
            model_name='order',
            name='total_ammunt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='total_items_sale',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
