# Generated by Django 4.0.4 on 2022-05-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_price_products_purchasing_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='total_items_sale',
            new_name='number_of_items_saled',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_ammunt',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True),
        ),
    ]
