# Generated by Django 4.0.4 on 2022-06-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_total_items_sale_products_number_of_items_saled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
