# Generated by Django 4.0.4 on 2022-06-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_order_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='imei',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
