# Generated by Django 4.0.4 on 2022-06-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_orderitems_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_code',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
