# Generated by Django 4.0.4 on 2022-06-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_order_unique_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_ammunt',
            new_name='total_amount',
        ),
    ]
