# Generated by Django 4.0.4 on 2022-06-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_total_ammunt_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_address',
            new_name='warranty',
        ),
    ]
