# Generated by Django 3.2.12 on 2022-08-04 18:39

from django.db import migrations, models
import django.db.models.deletion
import project.apps.inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20220802_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_share', models.PositiveIntegerField()),
                ('owner_share', models.PositiveIntegerField()),
                ('business_share', models.PositiveIntegerField()),
                ('expense_share', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CashOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=project.apps.inventory.models.generate_join_code, max_length=10, unique=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
                ('sale_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sellerprofile')),
            ],
        ),
    ]
