# Generated by Django 3.2.12 on 2022-08-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20220804_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashorder',
            name='warranty',
            field=models.PositiveIntegerField(default=0, help_text='in days'),
        ),
    ]
