# Generated by Django 3.2.12 on 2022-08-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_cashorder_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
    ]
