# Generated by Django 3.2.12 on 2022-08-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_cashorder_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='status',
            field=models.CharField(choices=[('UP', 'up'), ('DOWN', 'DOWN')], default='UP', max_length=10),
        ),
    ]
