# Generated by Django 3.2.12 on 2022-08-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20220804_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashorder',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
