# Generated by Django 3.2.12 on 2022-08-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_cashorder_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='username',
            field=models.CharField(default=1, max_length=54),
            preserve_default=False,
        ),
    ]
