# Generated by Django 3.2.12 on 2022-08-05 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_sellerprofile_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='status',
            field=models.CharField(choices=[('UP', 'up'), ('DOWN', 'down')], default='UP', max_length=10),
        ),
        migrations.CreateModel(
            name='ReturnCashOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('NOT_INTERESTED', 'Not Interested'), ('ISSUE', 'Issue')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.cashorder')),
            ],
        ),
    ]
