# Generated by Django 3.2.12 on 2022-08-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20220805_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='returncashorder',
            name='return_amount',
            field=models.IntegerField(blank=True, help_text='To be filled automatically', null=True),
        ),
    ]
