# Generated by Django 3.2.12 on 2022-08-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_returncashorder_return_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashorder',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
