# Generated by Django 3.2.12 on 2022-08-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_returncashorder_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='business_share',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='seller_share',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_share',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_share',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
