# Generated by Django 3.2.12 on 2022-08-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_companyprofile_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMEINumber',
            fields=[
                ('number', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='imei_or_serial_number',
        ),
        migrations.AddField(
            model_name='cashorder',
            name='imei_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.imeinumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='imei_or_serial_number',
            field=models.ManyToManyField(blank=True, to='inventory.IMEINumber'),
        ),
    ]
