# Generated by Django 3.2.12 on 2022-08-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_products_available_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashorder',
            old_name='imei_number',
            new_name='imei_or_serial_number',
        ),
    ]
