# Generated by Django 3.2.12 on 2022-08-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20220820_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashorder',
            name='imei_or_serial_number',
        ),
        migrations.AddField(
            model_name='cashorder',
            name='imei_or_serial_number',
            field=models.ManyToManyField(to='inventory.IMEINumber'),
        ),
    ]
