# Generated by Django 3.2.12 on 2022-08-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_auto_20220820_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashorder',
            old_name='profit',
            new_name='profit_per_device',
        ),
        migrations.AddField(
            model_name='cashorder',
            name='total_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
