# Generated by Django 3.2.12 on 2022-08-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20220820_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashorder',
            name='product_stock',
        ),
        migrations.RemoveField(
            model_name='cashorder',
            name='profit_per_device',
        ),
    ]
