# Generated by Django 3.2.12 on 2022-08-20 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20220820_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashorder',
            name='imei_or_serial_number',
        ),
        migrations.RemoveField(
            model_name='cashorder',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='cashorder',
            name='warranty',
            field=models.PositiveIntegerField(default=0, help_text='days'),
        ),
        migrations.CreateModel(
            name='CashOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cash_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.cashorder')),
                ('imei_or_serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.imeinumber')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
