# Generated by Django 3.2.12 on 2022-08-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20220820_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashorderitem',
            name='quantity',
        ),
    ]
