# Generated by Django 3.2.12 on 2022-08-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_remove_cashorderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashorderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cashorderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
