# Generated by Django 3.2.12 on 2022-08-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20220820_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='business_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.companyprofile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.cashorder'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.sellerprofile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
