# Generated by Django 3.2.12 on 2022-08-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_auto_20220825_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_profit', models.IntegerField()),
                ('business_profit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='returncashorder',
            name='reason_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
