# Generated by Django 3.2.12 on 2022-08-26 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_claim_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credititem',
            name='product',
        ),
        migrations.AddField(
            model_name='credititem',
            name='product_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.productstockin'),
            preserve_default=False,
        ),
    ]
